server:
  port: 8086
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car_post_analytics
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers:localhost:9092
